config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root "posts#index"
  resources :homes
  resources :schools do
    resources :teachers
    resources :students
    resources :counselings
  end
  # resources :posts do
  #   resources :comments
  # end
  get "/posts/index", to: "posts#index"
  get "/posts/index_joins", to: "posts#index_joins"
  get "/posts/index_includes", to: "posts#index_includes"
  get "/posts/index_preload", to: "posts#index_preload"
  get "/posts/index_eager_load", to: "posts#index_eager_load"

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/counseling.rb
class Counseling < ActiveRecord::Base
  belongs_to :school
  belongs_to :teacher
  belongs_to :student
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :tags
end

app/models/school.rb
class School < ActiveRecord::Base
  mount_uploader :logo, LogoUploader
  has_many :counselings, dependent: :destroy
  has_many :teachers, dependent: :destroy
  has_many :students, dependent: :destroy
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school
  has_many :counselings
  has_many :teachers, :through => :counselings, dependent: :destroy
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school
  has_many :counselings
  has_many :students, :through => :counselings, dependent: :destroy
  def name_with_value
    "#{name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    # N+1 쿼리 발생
    result = []
    @posts = Post.all

    @posts.each do |post|
      result << {
        id: post.id,
        comments: post.comments
      }
    end

    render json: result
  end

  def index_joins
    result = []
    @posts = Post.all.joins(:comments)

    @posts.each do |post|
      result << {
        id: post.id,
        comments: post.comments
      }
    end

    render json: result
  end

  def index_includes
    result = []
    # @posts = Post.all.includes(:comments)
    @posts = Post.all.includes(:comments).where(comments: {body: 'Body 1'})

    @posts.each do |post|
      result << {
        id: post.id,
        comments: post.comments
      }
    end

    render json: result
  end

  def index_preload
    result = []
    # @posts = Post.all.preload(:comments)
    # @posts = Post.all.preload(:comments, :tags)
    # @posts = Post.all.preload(:comments).where(comments: {body: 'Body 1'})
    # @posts = Post.all.preload(:comments).where(posts: {body: 'Body 1'})

    @posts.each do |post|
      result << {
        id: post.id,
        comments: post.comments
      }
    end

    render json: result
  end


  def index_eager_load
    result = []
    # @posts = Post.all.eager_load(:comments)
    @posts = Post.all.eager_load(:comments).where(comments: {body: 'Body 1'})

    @posts.each do |post|
      result << {
        id: post.id,
        comments: post.comments
      }
    end

    render json: result
  end

  def create
    @post = Post.new
    @post.save
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/counselings_helper.rb
module CounselingsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
    #
    # messages = resource.errors.full_message.map { |msg| content_tag(:li, msg) }.join
    # sentence = I18n.t('errors.messages.not_saved',
    #                   count: resource.errors.count,
    #                   resource: resource.class.model_nmae.human.downcase)
    # html = <<-HTML
    # <div class="alert alert-danger alert-dismissible fade show" role="alert">
    #   <button type="button" class="close" data-dismiss="alert">&times;</button>
    #   <h6><b>#{sentence}</b></h6>
    #   #{messages}
    # </div>
    # HTML
    # html.html_safe
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<h1>Listing homes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.title %></td>
        <td><%= home.content %></td>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @home.content %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/posts/index.html.erb
<style>
    table {
        width: 50%;
        border: 1px solid #444444;
        border-collapse: collapse;
    }
    th, td {
        border: 1px solid #444444;
    }
</style>
<h1>Posts List</h1>
<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Action</th>
  </tr>
  <% @posts.each do |post| %>
    <tr>
      <td style="text-align: center;">
        <%= post.id %>
      </td>
      <td>
        <a href="/posts/<%= post.id %>">
          <%= post.title %>
        </a>
      </td>
      <td>
        <% post.comments.each do |comment| %>
          <%= comment.id %>
        <% end %>
        <%#= link_to "Show", school_path(school) %>
        <%#= link_to "Edit", edit_school_path(school)%>
        <%#= link_to "Delete", school_path(school), method: :delete, data: { confirm: "Are you sure? "} %>
      </td>
    </tr>
  <% end %>
</table>
<!--<a href="/schools/new">Add School</a>-->
<%#= link_to "Add School", new_school_path %>