config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root "posts#index"
  resources :homes
  resources :schools do
    resources :teachers
    resources :students
    resources :counselings
  end
  # resources :posts do
  #   resources :comments
  # end
  get "/posts/index", to: "posts#index"
  get "/posts/index_joins", to: "posts#index_joins"
  get "/posts/index_includes", to: "posts#index_includes"
  get "/posts/index_preload", to: "posts#index_preload"
  get "/posts/index_eager_load", to: "posts#index_eager_load"

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/counseling.rb
class Counseling < ActiveRecord::Base
  belongs_to :school
  belongs_to :teacher
  belongs_to :student
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :tags
end

app/models/school.rb
class School < ActiveRecord::Base
  mount_uploader :logo, LogoUploader
  has_many :counselings, dependent: :destroy
  has_many :teachers, dependent: :destroy
  has_many :students, dependent: :destroy
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school
  has_many :counselings
  has_many :teachers, :through => :counselings, dependent: :destroy
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :school
  has_many :counselings
  has_many :students, :through => :counselings, dependent: :destroy
  def name_with_value
    "#{name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :content)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # before_action :authenticate_user!
  def new
    @school = School.new
  end
  def create
    @school = School.new(school_params)
    @school.save
    redirect_to schools_path
  end
  def index
    @schools = School.all
  end
  def show
    # find(id) = find_by_id(id)
    # @school = School.find_by_id(params[:id])
    @school = School.find(params[:id])

    # @teachers = @school.teachers
    # @students = @school.students
  end
  def edit
    @school = School.find(params[:id])
  end
  def update
    @school = School.find(params[:id])
    if @school.update(school_params)
      redirect_to "/schools"
    else
      render "edit"
    end

  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy
    redirect_to "/schools"
    # redirect_to schools_path
  end


  private
  def school_params
    params.require(:school).permit(:name, :logo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/counselings_helper.rb
module CounselingsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
    #
    # messages = resource.errors.full_message.map { |msg| content_tag(:li, msg) }.join
    # sentence = I18n.t('errors.messages.not_saved',
    #                   count: resource.errors.count,
    #                   resource: resource.class.model_nmae.human.downcase)
    # html = <<-HTML
    # <div class="alert alert-danger alert-dismissible fade show" role="alert">
    #   <button type="button" class="close" data-dismiss="alert">&times;</button>
    #   <h6><b>#{sentence}</b></h6>
    #   #{messages}
    # </div>
    # HTML
    # html.html_safe
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/schools/_form.html.erb
<%= form_for :school, url: schools_path do |form| %>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
  <!--  <%#= form.label :city %><br>-->
  <%#= form.text_field :city %>
  <%= form.file_field :logo %>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/schools/edit.html.erb
<h2>Edit School Info</h2>

<%= form_for :school, url: { action: "update"}, method: :patch do |form| %>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to "Back to home", schools_path %>

app/views/schools/index.html.erb
<style>
  table {
      width: 50%;
      border: 1px solid #444444;
      border-collapse: collapse;
  }
  th, td {
      border: 1px solid #444444;
  }
</style>
<h1>Schools List</h1>
<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Action</th>
  </tr>
  <% @schools.each do |school| %>
    <tr>
      <td style="text-align: center;">
        <%= school.id %>
      </td>
      <td>
        <a href="/schools/<%= school.id %>">
          <%= school.name %>
        </a>
      </td>
      <td>
        <%= link_to "Show", school_path(school) %>
<!--        <a href="/schools/<%#= school.id %>/edit">Edit</a>-->
        <%= link_to "Edit", edit_school_path(school)%>
        <%= link_to "Delete", school_path(school), method: :delete, data: { confirm: "Are you sure? "} %>
      </td>
    </tr>
<% end %>
</table>
<!--<a href="/schools/new">Add School</a>-->
<%= link_to "Add School", new_school_path %>

app/views/schools/new.html.erb
<h2>School Register Page</h2>

<%= render "form" %>
<%= link_to "Back to home", schools_path %>

app/views/schools/show.html.erb
<style>
    table {
        width: 50%;
        border: 1px solid #444444;
        border-collapse: collapse;
    }
    th, td {
        border: 1px solid #444444;
    }
</style>
<h2>School Info</h2>
<h3>School Name : <%= @school.name %></h3>


<h3>Teacher List</h3>
<table>
  <tr>
    <th>Teacher Id</th>
    <th>Name</th>
    <th>Subject</th>
    <th>Action</th>
  </tr>
  <%= render @school.teachers %>
</table>

<h3>Student List</h3>
<table>
  <tr>
    <th>Student Id</th>
    <th>Name</th>
    <th>Action</th>
  </tr>
  <%= render @school.students %>
</table>

<h3>Counseling List</h3>
<table>
  <tr>
    <th>Counseling Id</th>
    <th>Counsellor Name</th>
    <th>Student Name</th>
    <th>Date</th>
  </tr>
  <% @school.counselings.each do |counselling| %>
    <tr>
      <td style="text-align: center;">
        <%= counselling.id %>
      </td>
      <td>
        <%= @school.teachers.find(counselling.teacher_id).name %>
      </td>
      <td>
        <%= @school.students.find(counselling.student_id).name %>
      </td>
      <td>
        <%= counselling.appointment_date %>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to "Add Teacher", new_school_teacher_path(@school) %> |
<%= link_to "Add Student", new_school_student_path(@school) %> |
<%= link_to "Add Counseling", new_school_counseling_path(@school) %> |
<%= link_to "Back to home", schools_path %>